#!/bin/sh
# Alpine Base Container Entrypoint
# Generated by Container Template Engine

set -e

# Initialize container
echo "Starting {{ template_name }} container..."
echo "User: $(whoami)"
echo "Platform: ${TARGETPLATFORM:-unknown}"
echo "Timezone: ${TZ:-UTC}"

# Run any initialization scripts
if [ -d "/docker-entrypoint-init.d" ]; then
    for f in /docker-entrypoint-init.d/*; do
        case "$f" in
            *.sh)     echo "Running $f"; . "$f" ;;
            *.sql)    echo "Ignoring $f (no database)" ;;
            *)        echo "Ignoring $f" ;;
        esac
        echo
    done
fi

# Execute the command
exec "$@"
