---
# Based on https://github.com/bfra-me/works/blob/7217b637351a0b251d1d0c2158614210c7efdad0/.github/actions/pnpm-install/action.yaml
name: Setup
description: Setup build environment and install dependencies

inputs:
  cache-version:
    default: '0'
    description: Cache version. Can be incremented to invalidate the cache.
    required: false

runs:
  steps:
    - name: Install mise
      env:
        MISE_VERSION: 2025.11.1 # renovate: datasource=github-releases packageName=jdx/mise
      uses: jdx/mise-action@d16887ba50704baed7de72bd1e82e04391e4457a # v3.5.0
      with:
        version: ${{ env.MISE_VERSION }}

    - name: Setup Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        cache: poetry
        python-version-file: 'pyproject.toml'

    - name: Install dependencies
      run: poetry install
      shell: 'bash -Eeuo pipefail {0}'

  using: composite
