---
# Based on https://github.com/bfra-me/works/blob/7217b637351a0b251d1d0c2158614210c7efdad0/.github/actions/pnpm-install/action.yaml
name: Setup
description: Setup build environment and install dependencies

inputs:
  cache-version:
    default: '0'
    description: Cache version. Can be incremented to invalidate the cache.
    required: false

runs:
  steps:
    - name: Install mise
      env:
        MISE_VERSION: 2026.2.18 # renovate: datasource=github-releases packageName=jdx/mise
      uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
      with:
        version: ${{ env.MISE_VERSION }}

    - name: Cache Poetry dependencies
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: .venv
        key: poetry-${{ runner.os }}-${{ inputs.cache-version }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          poetry-${{ runner.os }}-${{ inputs.cache-version }}-

    - name: Install dependencies
      run: poetry install
      shell: 'bash -Eeuo pipefail {0}'

  using: composite
