# AI Configuration for Container Template System
# Configure AI providers and capabilities

ai:
  # Enable/disable AI features globally
  enabled: true

  # Default AI provider (ollama, openai, anthropic)
  default_provider: 'ollama'

  # Provider configurations
  providers:
    ollama:
      enabled: true
      base_url: 'http://localhost:11434'
      models:
        chat: 'llama3.2'
        code: 'codellama'
        analysis: 'mistral'
      timeout: 30

    openai:
      enabled: false
      api_key_env: 'OPENAI_API_KEY'
      models:
        chat: 'gpt-4'
        code: 'gpt-4'
        analysis: 'gpt-3.5-turbo'
      timeout: 30
      max_tokens: 4000

    anthropic:
      enabled: false
      api_key_env: 'ANTHROPIC_API_KEY'
      models:
        chat: 'claude-3-sonnet-20240229'
        code: 'claude-3-sonnet-20240229'
        analysis: 'claude-3-haiku-20240307'
      timeout: 30
      max_tokens: 4000

  # AI feature configurations
  features:
    template_recommendation:
      enabled: true
      confidence_threshold: 0.7
      max_suggestions: 5

    parameter_inference:
      enabled: true
      auto_apply_threshold: 0.9
      scan_files: ['package.json', 'requirements.txt', 'go.mod', 'Cargo.toml', 'composer.json']

    code_analysis:
      enabled: true
      security_scan: true
      performance_analysis: true
      best_practices: true

    natural_language:
      enabled: true
      conversation_memory: true
      max_conversation_length: 20

    predictive_maintenance:
      enabled: true
      analytics_retention_days: 365
      suggestion_frequency: 'weekly'

    documentation_generation:
      enabled: true
      auto_generate: false
      include_examples: true

    test_generation:
      enabled: true
      test_frameworks: ['jest', 'pytest', 'go-test', 'cargo-test']
      coverage_target: 80

  # Caching and performance
  cache:
    enabled: true
    ttl_hours: 24
    max_size_mb: 100

  # Analytics and tracking
  analytics:
    enabled: true
    database_path: 'template_analytics.db'
    collect_usage: true
    collect_performance: true
    privacy_mode: false
